# Default values for the starbucks-app Helm chart.

replicaCount: 1

image:
  repository: greekgodacr.azurecr.io/starbucks-app
  pullPolicy: IfNotPresent
  tag: "latest"  # Use the existing image tag from your ACR

service:
  type: LoadBalancer
  port: 80

container:
  port: 3000
